#define BLACK 0x0
#define BLUE 0x1
#define GREEN 0x2
#define AQUA 0x3
#define RED 0x4
#define PURPLE 0x5
#define YELLOW 0x6
#define WHITE 0x7
#define GREY 0x8
#define LIGHT_BLUE 0x9
#define LIGHT_GREEN 0xA
#define LIGHT_AQUA 0xB
#define LIGHT_RED 0xC
#define LIGHT_PURPLE 0xD
#define LIGHT_YELLOW 0xE
#define BRIGHT_WHITE 0xF
